"""Huey tasks — wraps MotherlabsEngine.compile() for async execution.

Each task creates its own MotherlabsEngine instance (stateless).
retries=0 because the engine has its own retry logic via FailoverClient.
"""

import logging
import signal
import time
from typing import Any, Dict, Optional

from worker.config import huey
import adapters  # noqa: F401 — registers built-in domain adapters

logger = logging.getLogger("motherlabs.worker")

TASK_TIMEOUT = 300  # 5 minutes — kills hung compilations


class TaskTimeout(Exception):
    pass


def _timeout_handler(signum, frame):
    raise TaskTimeout(f"Compilation exceeded {TASK_TIMEOUT}s timeout")


def _detect_provider(api_key: str, llm_provider: Optional[str] = None) -> str:
    """Detect LLM provider from key prefix or explicit parameter."""
    if llm_provider:
        return llm_provider
    if api_key.startswith("sk-ant-"):
        return "claude"
    if api_key.startswith("sk-"):
        return "openai"
    if api_key.startswith("xai-"):
        return "grok"
    return "claude"  # Default to Claude


def _generate_trust_report(
    trust: Dict[str, Any],
    blueprint: Dict[str, Any],
    domain: str,
    duration: float,
) -> str:
    """Generate human-readable TRUST_REPORT.md from trust indicators."""
    score = trust.get("overall_score", 0)
    badge = trust.get("verification_badge", "unknown")
    fidelity = trust.get("fidelity_scores", {})
    gaps = trust.get("gap_report", [])
    silence = trust.get("silence_zones", [])
    coverage = trust.get("dimensional_coverage", {})
    chain_len = trust.get("derivation_chain_length", 0)
    comp_count = trust.get("component_count", 0)
    rel_count = trust.get("relationship_count", 0)
    constraint_count = trust.get("constraint_count", 0)
    method_cov = trust.get("method_coverage", 0)

    lines = [
        "# Trust Report",
        "",
        f"**Domain:** {domain}",
        f"**Overall Score:** {score:.1f}%",
        f"**Badge:** {badge}",
        f"**Compilation Time:** {duration}s",
        "",
        "## Summary",
        "",
        f"- {comp_count} components, {rel_count} relationships, {constraint_count} constraints",
        f"- Method coverage: {method_cov:.0f}%",
        f"- Provenance chain depth: {chain_len} strata",
        "",
        "## Fidelity Scores",
        "",
    ]
    for dim, val in sorted(fidelity.items()):
        bar_val = val / 100 if val > 1 else val
        bar = "█" * int(bar_val * 20) + "░" * (20 - int(bar_val * 20))
        lines.append(f"- **{dim}:** {val:.1f}% {bar}")
    lines.append("")

    if coverage:
        lines.append("## Dimensional Coverage")
        lines.append("")
        for dim, val in sorted(coverage.items()):
            lines.append(f"- {dim}: {val:.1f}%")
        lines.append("")

    if gaps:
        lines.append("## Gaps")
        lines.append("")
        for gap in gaps:
            lines.append(f"- {gap}")
        lines.append("")

    if silence:
        lines.append("## Silence Zones")
        lines.append("")
        for zone in silence:
            lines.append(f"- {zone}")
        lines.append("")

    lines.extend([
        "---",
        "*Generated by Motherlabs Semantic Compiler. Every score traces to input provenance.*",
    ])
    return "\n".join(lines)


def _generate_deployment_templates(
    project_name: str,
    entry_point: str,
    has_runtime: bool,
) -> Dict[str, str]:
    """Generate deterministic deployment files for project ZIP."""
    templates: Dict[str, str] = {}

    # .gitignore
    templates[".gitignore"] = "\n".join([
        "__pycache__/",
        "*.py[cod]",
        "*$py.class",
        "*.egg-info/",
        "dist/",
        "build/",
        ".eggs/",
        "*.egg",
        ".env",
        ".venv/",
        "venv/",
        "env/",
        "*.sqlite3",
        "*.db",
        ".motherlabs/*.log",
        "",
    ])

    # Dockerfile
    ep = entry_point or "main.py"
    templates["Dockerfile"] = "\n".join([
        "FROM python:3.12-slim",
        "",
        "WORKDIR /app",
        "",
        "COPY requirements.txt .",
        "RUN pip install --no-cache-dir -r requirements.txt",
        "",
        "COPY . .",
        "",
        f'CMD ["python", "{ep}"]',
        "",
    ])

    # .env.example
    env_lines = [
        "# Environment configuration",
        f"# Project: {project_name}",
        "",
    ]
    if has_runtime:
        env_lines.extend([
            "# LLM provider (if agent system)",
            "ANTHROPIC_API_KEY=",
            "OPENAI_API_KEY=",
            "",
        ])
    env_lines.extend([
        "# Application",
        "PORT=8080",
        "LOG_LEVEL=INFO",
        "",
    ])
    templates[".env.example"] = "\n".join(env_lines)

    # docker-compose.yml
    templates["docker-compose.yml"] = "\n".join([
        "version: '3.8'",
        "services:",
        f"  {project_name or 'app'}:",
        "    build: .",
        "    ports:",
        '      - "${PORT:-8080}:8080"',
        "    env_file:",
        "      - .env",
        "    restart: unless-stopped",
        "",
    ])

    # .github/workflows/ci.yml
    templates[".github/workflows/ci.yml"] = "\n".join([
        f"name: CI — {project_name}",
        "",
        "on:",
        "  push:",
        "    branches: [main]",
        "  pull_request:",
        "    branches: [main]",
        "",
        "jobs:",
        "  test:",
        "    runs-on: ubuntu-latest",
        "    steps:",
        "      - uses: actions/checkout@v4",
        "      - uses: actions/setup-python@v5",
        "        with:",
        "          python-version: '3.12'",
        "      - run: pip install -r requirements.txt",
        "      - run: python -m pytest tests/ -v",
        "",
    ])

    return templates


def _generate_mermaid_diagram(blueprint: Dict[str, Any]) -> str:
    """Generate Mermaid graph from blueprint components and relationships."""
    components = blueprint.get("components", [])
    relationships = blueprint.get("relationships", [])
    if not components:
        return ""

    lines = ["graph TD"]
    # Node definitions
    for comp in components:
        name = comp.get("name", "unknown")
        ctype = comp.get("type", "component")
        safe_id = name.replace(" ", "_").replace("-", "_")
        if ctype in ("service", "actor", "agent"):
            lines.append(f"    {safe_id}[/{name}/]")
        elif ctype in ("model", "entity", "data"):
            lines.append(f"    {safe_id}[({name})]")
        elif ctype in ("interface", "api", "endpoint"):
            lines.append(f"    {safe_id}{{{{{name}}}}}")
        else:
            lines.append(f"    {safe_id}[{name}]")

    # Edge definitions
    for rel in relationships:
        src = rel.get("from_component", "").replace(" ", "_").replace("-", "_")
        tgt = rel.get("to_component", "").replace(" ", "_").replace("-", "_")
        rtype = rel.get("type", "")
        if src and tgt:
            label = rtype.replace("_", " ") if rtype else ""
            if label:
                lines.append(f"    {src} -->|{label}| {tgt}")
            else:
                lines.append(f"    {src} --> {tgt}")

    return "\n".join(lines)


@huey.task(retries=0, context=True)
def compile_task(
    description: str,
    domain: str = "software",
    provider: Optional[str] = None,
    enrich: bool = False,
    canonical_components: Optional[list] = None,
    canonical_relationships: Optional[list] = None,
    llm_api_key_enc: Optional[str] = None,
    llm_provider: Optional[str] = None,
    task=None,
) -> Dict[str, Any]:
    """Run a compilation asynchronously.

    Returns a serializable dict (CompileResult fields + metadata).
    llm_api_key_enc is encrypted — never stored as plaintext in Huey DB.

    Uses context=True so Huey injects the task instance as the `task` kwarg,
    giving us task.id for progress tracking.
    """
    from core.engine import MotherlabsEngine
    from core.adapter_registry import get_adapter
    from core.trust import compute_trust_indicators, serialize_trust_indicators
    from worker.keystore import decrypt_if_present
    from worker.progress import write_progress

    start = time.time()
    task_id = task.id if task else None

    # Decrypt BYO LLM key (encrypted in API route, stored encrypted in Huey DB)
    llm_api_key = decrypt_if_present(llm_api_key_enc)

    # If BYO key provided but server has env var too, prefer BYO.
    # If no BYO key, pass None so create_client falls back to env var.
    effective_provider = provider or "auto"
    if llm_api_key:
        effective_provider = _detect_provider(llm_api_key, llm_provider)
    else:
        llm_api_key = None  # Explicit: let create_client use env var

    # Set timeout (Unix only — signal.SIGALRM not available on Windows)
    old_handler = None
    try:
        old_handler = signal.signal(signal.SIGALRM, _timeout_handler)
        signal.alarm(TASK_TIMEOUT)
    except (AttributeError, ValueError):
        pass  # Windows or non-main thread — skip timeout

    try:
        adapter = get_adapter(domain)
        engine = MotherlabsEngine(
            api_key=llm_api_key,
            provider=effective_provider,
            pipeline_mode="staged",
            domain_adapter=adapter,
        )

        # Progress callback for live compilation view
        def _on_progress(stage: str, index: int, insight: str = "", **kwargs):
            if task_id:
                try:
                    write_progress(
                        task_id, stage, index, insight,
                        structured_insight=kwargs.get("structured_insight"),
                        difficulty=kwargs.get("difficulty"),
                        escalations=kwargs.get("escalations"),
                        human_decisions=kwargs.get("human_decisions"),
                    )
                except Exception:
                    pass  # Non-critical — don't fail compilation over progress tracking

        result = engine.compile(
            description=description,
            canonical_components=canonical_components,
            canonical_relationships=canonical_relationships,
            enrich=enrich,
            progress_callback=_on_progress,
        )

        blueprint = result.blueprint if hasattr(result, "blueprint") else {}
        verification = result.verification if hasattr(result, "verification") else {}
        context_graph = result.context_graph if hasattr(result, "context_graph") else {}
        dim_meta = result.dimensional_metadata if hasattr(result, "dimensional_metadata") else {}
        interface_map = result.interface_map if hasattr(result, "interface_map") else {}
        intent_keywords = context_graph.get("keywords", []) if isinstance(context_graph, dict) else []

        trust_indicators = compute_trust_indicators(
            blueprint=blueprint,
            verification=verification,
            context_graph=context_graph,
            dimensional_metadata=dim_meta,
            intent_keywords=intent_keywords,
        )
        trust_data = serialize_trust_indicators(trust_indicators)

        duration = time.time() - start
        success = result.success if hasattr(result, "success") else False

        # Materialize code output if compilation succeeded
        materialized: Dict[str, str] = {}
        if success and blueprint.get("components"):
            try:
                emission = engine.emit_code(blueprint)
                if hasattr(emission, "generated_code") and emission.generated_code:
                    materialized = dict(emission.generated_code)
            except Exception as emit_err:
                logger.warning("Code emission failed: %s", emit_err)

        # Post-emission stub detection
        stub_report = None
        if materialized:
            try:
                from core.agent_emission import detect_stub_methods
                stubs, stub_count, total_methods = detect_stub_methods(materialized)
                stub_ratio = stub_count / total_methods if total_methods else 0.0
                stub_report = {
                    "stub_count": stub_count,
                    "total_methods": total_methods,
                    "stub_ratio": round(stub_ratio, 3),
                    "stubs": [
                        {"file": s.file, "class": s.class_name, "method": s.method_name}
                        for s in stubs[:50]
                    ],
                }
                if stub_count > 0:
                    logger.warning(
                        "Compilation: %d/%d methods are stubs (%.0f%%)",
                        stub_count, total_methods, stub_ratio * 100,
                    )
            except Exception as stub_err:
                logger.warning("Stub detection failed: %s", stub_err)

        # Build project files for zip download
        project_files: Dict[str, str] = {}
        entry_point = ""
        project_name = ""
        if materialized:
            try:
                from core.project_writer import build_project_in_memory, _infer_project_name, ProjectConfig
                config = ProjectConfig(
                    runtime_capabilities=adapter.runtime,
                )
                manifest = build_project_in_memory(
                    materialized,
                    blueprint,
                    config=config,
                    entity_types=adapter.vocabulary.entity_types or None,
                    file_extension=adapter.materialization.file_extension,
                )
                project_files = dict(manifest.file_contents)
                entry_point = manifest.entry_point
                project_name = _infer_project_name(blueprint)
            except Exception as pw_err:
                logger.warning("Project build failed: %s", pw_err)

        # Adaptive emission — enrich project files based on blueprint analysis
        if success and project_files and materialized:
            try:
                from core.adaptive_emission import compose_adaptive_artifacts
                project_files = compose_adaptive_artifacts(
                    blueprint=blueprint,
                    materialized_code=materialized,
                    project_files=project_files,
                    domain=domain,
                    has_runtime=adapter.runtime is not None,
                )
            except Exception as adapt_err:
                logger.warning("Adaptive emission failed: %s", adapt_err)

        # Bundle intelligence artifacts into project ZIP
        if success and project_files:
            try:
                import json as _json

                # blueprint.json — full ontology
                project_files[".motherlabs/blueprint.json"] = _json.dumps(
                    blueprint, indent=2, default=str
                )

                # context_graph.json — reasoning trace
                if context_graph:
                    project_files[".motherlabs/context_graph.json"] = _json.dumps(
                        context_graph, indent=2, default=str
                    )

                # interfaces.json — integration contracts
                if interface_map:
                    project_files[".motherlabs/interfaces.json"] = _json.dumps(
                        interface_map, indent=2, default=str
                    )

                # TRUST_REPORT.md — human-readable trust assessment
                if trust_data:
                    project_files["TRUST_REPORT.md"] = _generate_trust_report(
                        trust_data, blueprint, domain, round(duration, 2)
                    )

                # architecture.mmd — Mermaid diagram from relationships
                mermaid = _generate_mermaid_diagram(blueprint)
                if mermaid:
                    project_files[".motherlabs/architecture.mmd"] = mermaid

                # UNDERSTANDING.md — the comprehension mirror
                try:
                    from core.project_writer import _generate_understanding_md
                    from core.resolution import serialize_resolution_report, resolve_unresolved
                    # Resolution already applied in engine — extract data from blueprint
                    resolution_data = {
                        "resolved_count": len(blueprint.get("resolutions", [])),
                        "acknowledged_count": len(blueprint.get("acknowledged_unknowns", [])),
                        "items": [
                            {
                                "original": r.get("original", ""),
                                "resolution_type": r.get("type", ""),
                                "resolution": r.get("resolution", ""),
                                "evidence": r.get("evidence", []),
                            }
                            for r in blueprint.get("resolutions", [])
                        ],
                    }
                    project_files["UNDERSTANDING.md"] = _generate_understanding_md(
                        blueprint=blueprint,
                        original_input=description,
                        trust_data=trust_data,
                        resolution_data=resolution_data,
                        mermaid_diagram=mermaid or "",
                    )
                except Exception as understand_err:
                    logger.warning("UNDERSTANDING.md generation failed: %s", understand_err)

                # YAML compilation output for .motherlabs/
                try:
                    from core.compilation_output import build_flat_output
                    yaml_output = build_flat_output(blueprint, trust_data, context_graph)
                    for ypath, ycontent in yaml_output.items():
                        project_files[f".motherlabs/{ypath}"] = ycontent
                except Exception as yaml_err:
                    logger.warning("YAML output failed: %s", yaml_err)

                # Deployment templates (Dockerfile, .gitignore, CI, etc.)
                deploy_files = _generate_deployment_templates(
                    project_name=project_name,
                    entry_point=entry_point,
                    has_runtime=adapter.runtime is not None,
                )
                for fname, content in deploy_files.items():
                    # Don't overwrite existing files from project_writer
                    if fname not in project_files:
                        project_files[fname] = content

            except Exception as bundle_err:
                logger.warning("Intelligence bundling failed: %s", bundle_err)

        # Benchmark quality scoring (uses project_files so tests are included)
        benchmark_data = None
        if project_files:
            try:
                from core.benchmark import benchmark_project, serialize_benchmark
                bench = benchmark_project(
                    project_files, blueprint, trust_data, gen_label="compile",
                )
                benchmark_data = serialize_benchmark(bench)
                logger.info(
                    "Benchmark: composite=%.1f%% D5_tests=%.2f D3_stubs=%.2f",
                    bench.composite_score * 100,
                    bench.dimensions.get("D5_test_reality", 0),
                    bench.dimensions.get("D3_stub_ratio", 0),
                )
            except Exception as bench_err:
                logger.warning("Benchmark scoring failed: %s", bench_err)

        # Corpus auto-ingest: feed successful compilations back for L2 learning
        if success and blueprint.get("components"):
            try:
                from persistence.corpus import Corpus
                corpus = Corpus()
                corpus.store(
                    input_text=description,
                    context_graph=context_graph,
                    blueprint=blueprint,
                    insights=getattr(result, "structured_insights", []) or [],
                    success=True,
                    provider=effective_provider,
                    verification_score=trust_data.get("overall_score", 0) / 100.0,
                )
            except Exception as corpus_err:
                logger.warning("Corpus auto-ingest failed: %s", corpus_err)

        # Build yaml_output for API response (separate from project_files)
        yaml_output: Dict[str, str] = {}
        try:
            from core.compilation_output import build_flat_output
            yaml_output = build_flat_output(blueprint, trust_data, context_graph)
        except Exception:
            pass

        logger.info("Compilation completed: domain=%s duration=%.1fs success=%s", domain, duration, success)
        return {
            "input_text": description,
            "success": success,
            "blueprint": blueprint,
            "materialized_output": materialized,
            "trust": trust_data,
            "verification": verification,
            "context_graph": context_graph,
            "dimensional_metadata": dim_meta,
            "interface_map": interface_map,
            "domain": domain,
            "adapter_version": adapter.version,
            "duration_seconds": round(duration, 2),
            "project_files": project_files,
            "entry_point": entry_point,
            "project_name": project_name,
            "structured_insights": getattr(result, "structured_insights", []),
            "difficulty": getattr(result, "difficulty", {}),
            "semantic_nodes": getattr(result, "semantic_nodes", []),
            "blocking_escalations": getattr(result, "blocking_escalations", []),
            "stub_report": stub_report,
            "benchmark": benchmark_data,
            "yaml_output": yaml_output,
            "error": None,
        }

    except TaskTimeout:
        duration = time.time() - start
        logger.error(
            "DEAD LETTER: Compilation timed out after %.0fs: domain=%s description=%.100s",
            duration, domain, description,
        )
        return {
            "success": False,
            "blueprint": {},
            "trust": {},
            "verification": {},
            "context_graph": {},
            "dimensional_metadata": {},
            "interface_map": {},
            "domain": domain,
            "adapter_version": "unknown",
            "duration_seconds": round(duration, 2),
            "error": f"Compilation timed out after {TASK_TIMEOUT}s. Try a shorter description or 'fast' trust level.",
        }

    except Exception as e:
        duration = time.time() - start
        logger.exception(
            "DEAD LETTER: Compilation failed after %.1fs: domain=%s error=%s",
            duration, domain, str(e),
        )
        return {
            "success": False,
            "blueprint": {},
            "trust": {},
            "verification": {},
            "context_graph": {},
            "dimensional_metadata": {},
            "interface_map": {},
            "domain": domain,
            "adapter_version": "unknown",
            "duration_seconds": round(duration, 2),
            "error": str(e),
        }

    finally:
        # Clear timeout
        try:
            signal.alarm(0)
            if old_handler is not None:
                signal.signal(signal.SIGALRM, old_handler)
        except (AttributeError, ValueError):
            pass
