"""
Mother thought journal — persistence for internal thoughts.

LEAF module. Stdlib + sqlite3 only. No imports from core/ or mother/.

Stores thoughts generated by the metabolism system. Provides retrieval
for context enrichment (surfaceable thoughts) and consolidation
(subjects that recur across sessions).

Follows the exact pattern of journal.py (BuildJournal).
"""

import sqlite3
import time
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional


@dataclass(frozen=True)
class ThoughtRecord:
    """Single persisted thought."""

    record_id: int = 0
    timestamp: float = 0.0
    thought_type: str = ""
    disposition: str = "internal"
    subject: str = ""
    trigger: str = ""
    depth: float = 0.0
    mode: str = ""
    surfaced: bool = False
    session_id: str = ""


_CREATE_TABLE = """
CREATE TABLE IF NOT EXISTS thought_journal (
    record_id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp REAL NOT NULL,
    thought_type TEXT NOT NULL DEFAULT '',
    disposition TEXT NOT NULL DEFAULT 'internal',
    subject TEXT NOT NULL DEFAULT '',
    trigger TEXT NOT NULL DEFAULT '',
    depth REAL NOT NULL DEFAULT 0.0,
    mode TEXT NOT NULL DEFAULT '',
    surfaced INTEGER NOT NULL DEFAULT 0,
    session_id TEXT NOT NULL DEFAULT ''
)
"""


class ThoughtJournal:
    """SQLite-backed thought journal. Stores in existing history.db."""

    def __init__(self, db_path: Path):
        self._db_path = db_path
        self._conn = sqlite3.connect(str(db_path))
        self._conn.execute("PRAGMA journal_mode=WAL")
        self._conn.execute(_CREATE_TABLE)
        self._conn.commit()

    def record(self, rec: ThoughtRecord) -> int:
        """Record a thought. Returns the new record_id."""
        ts = rec.timestamp if rec.timestamp > 0 else time.time()
        cursor = self._conn.execute(
            """INSERT INTO thought_journal
               (timestamp, thought_type, disposition, subject, trigger,
                depth, mode, surfaced, session_id)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                ts,
                rec.thought_type,
                rec.disposition,
                rec.subject,
                rec.trigger,
                rec.depth,
                rec.mode,
                1 if rec.surfaced else 0,
                rec.session_id,
            ),
        )
        self._conn.commit()
        return cursor.lastrowid

    def recent(self, limit: int = 10) -> List[ThoughtRecord]:
        """Return most recent thoughts, newest first."""
        rows = self._conn.execute(
            "SELECT * FROM thought_journal ORDER BY timestamp DESC LIMIT ?",
            (limit,),
        ).fetchall()
        return [self._row_to_record(r) for r in rows]

    def surfaceable(self, limit: int = 5) -> List[ThoughtRecord]:
        """Return thoughts with disposition='surface' not yet surfaced."""
        rows = self._conn.execute(
            """SELECT * FROM thought_journal
               WHERE disposition = 'surface' AND surfaced = 0
               ORDER BY timestamp DESC LIMIT ?""",
            (limit,),
        ).fetchall()
        return [self._row_to_record(r) for r in rows]

    def mark_surfaced(self, record_id: int) -> None:
        """Mark a thought as surfaced (shown to user)."""
        self._conn.execute(
            "UPDATE thought_journal SET surfaced = 1 WHERE record_id = ?",
            (record_id,),
        )
        self._conn.commit()

    def subjects_for_consolidation(self, min_count: int = 2) -> List[str]:
        """Return subjects that appear multiple times (candidates for consolidation)."""
        rows = self._conn.execute(
            """SELECT subject, COUNT(*) as cnt FROM thought_journal
               WHERE subject != ''
               GROUP BY subject HAVING cnt >= ?
               ORDER BY cnt DESC LIMIT 10""",
            (min_count,),
        ).fetchall()
        return [row[0] for row in rows]

    def close(self) -> None:
        """Close the database connection."""
        self._conn.close()

    @staticmethod
    def _row_to_record(row) -> ThoughtRecord:
        """Convert a database row tuple to ThoughtRecord."""
        return ThoughtRecord(
            record_id=row[0],
            timestamp=row[1],
            thought_type=row[2],
            disposition=row[3],
            subject=row[4],
            trigger=row[5],
            depth=row[6],
            mode=row[7],
            surfaced=bool(row[8]),
            session_id=row[9],
        )
